name: c_template
variables:
  - build_type: debug
  - mugglec_tag: v1.4.4
source:
  maintainer: mugglewei
  name: c_template
  tag: 1.0.0
build:
  fat_pkg: true
deps:
  - maintainer: mugglewei
    name: mugglec
    tag: ${mugglec_tag}
jobs:
  build:
    steps:
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
          cmake --build ${HPB_BUILD_DIR};
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    steps:
      - name: package
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack --copy-to ${HPB_ROOT_DIR}/dist;
