name: use_openssl
variables:
  - build_type: debug
  - openssl_tag: openssl-3.1.0
  - mugglec_tag: v1.0.2
source:
  maintainer: mugglewei
  name: use_openssl
  tag: 1.0.0
build:
  fat_pkg: true
deps:
  - maintainer: openssl
    name: openssl
    tag: ${openssl_tag}
  - maintainer: mugglewei
    name: mugglec
    tag: ${mugglec_tag}
jobs:
  build:
    steps:
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
          cmake --build ${HPB_BUILD_DIR};
  package:
    steps:
      - name: package
        run: >
          cd ${HPB_TASK_DIR};
          cmake --build ${HPB_BUILD_DIR} --target install;
          hpb pack -o ${HPB_ROOT_DIR}/_artifacts;
