version: "6.0.2"
services:
  mongo:
    image: "mongo:6.0.2"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker_volume/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wsz123
  mongo-express:
    image: "mongo-express:0.54.0"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: wsz123
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
