name: mariadb_connector_c
variables:
  - build_type: release
  - mariadb_connector_c_tag: v3.3.5
  - mariadb_connector_c_url: https://github.com/mariadb-corporation/mariadb-connector-c.git
  - openssl_tag: openssl-3.1.0
source:
  maintainer: mariadb
  name: mariadb_connector_c
  tag: ${mariadb_connector_c_tag}
  repo_kind: git
  repo_url: ${mariadb_connector_c_url}
  git_depth: 1
deps:
  - name: openssl
    maintainer: openssl
    tag: ${openssl_tag}
jobs:
  build:
    steps:
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DREMOTEIO_PLUGIN_TYPE=OFF \
            -DAUTH_GSSAPI_PLUGIN_TYPE=OFF \
            -DWITH_UNIT_TESTS=OFF \
            -DWITH_EXTERNAL_ZLIB=ON \
            -DWITH_CURL=OFF;
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
