version: "7.0.4"
services:
  redis:
    image: "redis:7.0.4-alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volume/data:/data
      - ./redis.conf:/redis.conf:ro
    command: "redis-server /redis.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
