name: use_mysqlclient
variables:
  - build_type: release
  - mugglec_tag: v1.2.4
source:
  maintainer: mugglewei
  name: use_mysqlclient
  tag: v1.0.0
deps:
  - maintainer: mugglewei
    name: mugglec
    tag: ${mugglec_tag}
jobs:
  build:
    steps:
      - name: extra_download
        run: >
          ${HPB_ROOT_DIR}/download_mysqlclient.sh;
          cp -r ${HPB_ROOT_DIR}/_deps/mysqlclient/* ${HPB_DEPS_DIR}/;
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_PREFIX_PATH="${HPB_DEPS_DIR};${HPB_ROOT_DIR}/_deps/mysqlclient" \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
