version: "1.23.1"
services:
  nginx:
    image: "nginx:1.23.1-alpine"
    restart: always
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
  serv1:
    build: ./hello-service
    image: hello-service:0.0.1
    ports:
      - 10001:8080
    environment:
      - service_number=1
  serv2:
    build: ./hello-service
    image: hello-service:0.0.1
    ports:
      - 10002:8080
    environment:
      - service_number=2
  serv3:
    build: ./hello-service
    image: hello-service:0.0.1
    ports:
      - 10003:8080
    environment:
      - service_number=3
  serv4:
    build: ./hello-service
    image: hello-service:0.0.1
    ports:
      - 10004:8080
    environment:
      - service_number=4
  serv5:
    build: ./hello-service
    image: hello-service:0.0.1
    ports:
      - 10005:8080
    environment:
      - service_number=5
