include(FindPackageHandleStandardArgs)

set(mariadb_connector_cpp_name mariadbcpp)

find_path(MARIADB_CONNECTOR_CPP_INCLUDE_DIR
	NAMES conncpp.hpp
	PATH_SUFFIXES mariadb
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH)
find_library(MARIADB_CONNECTOR_CPP_LIBRARIES
	NAMES ${mariadb_connector_cpp_name} 
	PATH_SUFFIXES lib/mariadb
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH)

if (MSVC AND BUILD_SHARED_LIBS)
	find_path(MARIADB_CONNECTOR_CPP_RUNTIMES
		NAMES ${mariadb_connector_cpp_name}.dll
		PATH_SUFFIXES lib/mariadb
		NO_SYSTEM_ENVIRONMENT_PATH
		NO_CMAKE_SYSTEM_PATH)
	find_package_handle_standard_args(MARIADB_CONNECTOR_CPP REQUIRED_VARS
		MARIADB_CONNECTOR_CPP_INCLUDE_DIR
		MARIADB_CONNECTOR_CPP_LIBRARIES
		MARIADB_CONNECTOR_CPP_RUNTIMES)
else()
	find_package_handle_standard_args(MARIADB_CONNECTOR_CPP REQUIRED_VARS
		MARIADB_CONNECTOR_CPP_INCLUDE_DIR
		MARIADB_CONNECTOR_CPP_LIBRARIES)
endif()

if (MARIADB_CONNECTOR_CPP_FOUND)
	message("# find mariadb include dir: ${MARIADB_CONNECTOR_CPP_INCLUDE_DIR}")
	message("# find mariadb libraries: ${MARIADB_CONNECTOR_CPP_LIBRARIES}")
	if (MSVC AND BUILD_SHARED_LIBS)
		message("# find mariadb runtimes: ${MARIADB_CONNECTOR_CPP_RUNTIMES}")
	endif()
else()
	message("${MARIADB_CONNECTOR_CPP_INCLUDE_DIR}")
	message("${MARIADB_CONNECTOR_CPP_LIBRARIES}")
	message(FATAL_ERROR "Failed found mariadb")
endif()

SET(MARIADB_CONNECTOR_CPP_TARGET_NAME mariadbcpp)
if (BUILD_SHARED_LIBS)
	add_library(${MARIADB_CONNECTOR_CPP_TARGET_NAME} SHARED IMPORTED)
else()
	add_library(${MARIADB_CONNECTOR_CPP_TARGET_NAME} STATIC IMPORTED)
endif()

if (MSVC)
	if (BUILD_SHARED_LIBS)
		set_target_properties(${MARIADB_CONNECTOR_CPP_TARGET_NAME} PROPERTIES
			IMPORTED_IMPLIB "${MARIADB_CONNECTOR_CPP_LIBRARIES}"
			IMPORTED_LOCATION "${MARIADB_CONNECTOR_CPP_RUNTIMES}"
			INTERFACE_INCLUDE_DIRECTORIES "${MARIADB_CONNECTOR_CPP_INCLUDE_DIR}")
	else()
		set_target_properties(${MARIADB_CONNECTOR_CPP_TARGET_NAME} PROPERTIES
			IMPORTED_IMPLIB "${MARIADB_CONNECTOR_CPP_LIBRARIES}"
			IMPORTED_LOCATION "${MARIADB_CONNECTOR_CPP_LIBRARIES}"
			INTERFACE_INCLUDE_DIRECTORIES "${MARIADB_CONNECTOR_CPP_INCLUDE_DIR}")
	endif()
else()
	set_target_properties(${MARIADB_CONNECTOR_CPP_TARGET_NAME} PROPERTIES
		IMPORTED_IMPLIB "${MARIADB_CONNECTOR_CPP_LIBRARIES}"
		IMPORTED_LOCATION "${MARIADB_CONNECTOR_CPP_LIBRARIES}"
		INTERFACE_INCLUDE_DIRECTORIES "${MARIADB_CONNECTOR_CPP_INCLUDE_DIR}")
endif()