#ifndef CODEC_H_
#define CODEC_H_

#include <google/protobuf/message.h>

class Codec
{
public:
	/*
	 *  Serialize protobuf message to bytes array
	 *  @msg: protobuf message
	 *  @total_len: generated bytes length
	 */
	char* Serialize(const google::protobuf::Message *msg, int32_t &total_len);
	google::protobuf::Message* Deserialize(const char *bytes, int32_t &total_len);
};

#endif