version: "1.0.0"
services:
  hello:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        OS: alpine
        OS_VER: 3.17
        MUGGLEC_VER: 1.0.0-alpha.7
    image: registry.mugglewei.com/mugglec-hello:1.0.0
    restart: "no"
    volumes:
      - ./docker_volume/log:/usr/local/log
    command: "example_hello"
