FIND_PATH(PROTOBUF_INCLUDE_DIR
	NAMES google/protobuf/message.h
	PATH_SUFFIXES include
	PATHS ${CMAKE_PREFIX_PATH})

if (WIN32)
	FIND_LIBRARY(PROTOBUF_LIBS
		NAMES libprotobuf libprotobufd
		PATH_SUFFIXES lib
		PATHS ${CMAKE_PREFIX_PATH}
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	FIND_PATH(PROTOBUF_BIN_DIR
		NAMES protoc.exe
		PATH_SUFFIXES bin
		PATHS ${CMAKE_PREFIX_PATH}
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)
else()
	FIND_LIBRARY(PROTOBUF_LIBS
		NAMES protobuf protobufd
		PATH_SUFFIXES lib
		PATHS ${CMAKE_PREFIX_PATH}
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)

	FIND_PATH(PROTOBUF_BIN_DIR
		NAMES protoc
		PATH_SUFFIXES bin
		PATHS ${CMAKE_PREFIX_PATH}
		NO_CMAKE_ENVIRONMENT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH)
endif()

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ProtobufBin DEFAULT_MSG
    PROTOBUF_INCLUDE_DIR
	PROTOBUF_LIBS
	PROTOBUF_BIN_DIR)
