site_name: MkDocs
theme:
  name: material
  features:
    # 代码复制按钮
    - content.code.copy
nav:
  - index.md
  - c01.md

extra_javascript:
  - javascripts/mathjax@2.7.5/MathJax.min.js

markdown_extensions:
  # 数学支持
  - mdx_math
  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
