#ifndef CODEC_H_
#define CODEC_H_

#include <google/protobuf/message.h>

class Codec
{
public:
	/**
	 *  @brief Serialize protobuf message to bytes array
	 *
	 *  @param msg        protobuf message
	 *  @param total_len  generated bytes length
	 *
	 *  @return bytes array
	 */
	char* Serialize(const google::protobuf::Message *msg, int32_t &total_len);

	/**
	 * @brief Deserialize protobuf message from bytes array
	 *
	 * @param bytes
	 * @param total_len
	 *
	 * @return protobuf message
	 */
	google::protobuf::Message* Deserialize(const char *bytes, int32_t &total_len);
};

#endif
